# -*- coding: utf-8 -*-
"""Copy of Colourtrack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6bM6MzAIcG6lLS4vG9zsbukgZ6td2-s
"""
from flask import Flask, request, jsonify
from colorthief import ColorThief
from PIL import Image
import requests
import io

app = Flask(__name__)

# Function to get dominant colors from an image
def get_dominant_colors(image_url, num_colors=3):
    response = requests.get(image_url)
    if response.status_code == 200:
        image = io.BytesIO(response.content)
        color_thief = ColorThief(image)
        palette = color_thief.get_palette(color_count=num_colors)
        return palette
    return None

# API endpoint to suggest background colors
@app.route('/suggest-colors', methods=['POST'])
def suggest_colors():
    data = request.json
    if 'image_url' not in data:
        return jsonify({'error': 'No image URL provided'}), 400
    
    image_url = data['image_url']
    colors = get_dominant_colors(image_url)
    
    if colors:
        return jsonify({'suggested_colors': colors})
    else:
        return jsonify({'error': 'Could not process image'}), 500

# Homepage route to prevent 404 errors
@app.route('/')
def home():
    return "Welcome to the Background Color Suggestion API! Use the /suggest-colors endpoint."

if __name__ == "__main__":
    app.run(debug=True)
